name: Test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - run: yarn run playwright install-deps
      - run: yarn install --frozen-lockfile
      - run: yarn lint
      - run: yarn build # type check
      - run: yarn test
      - uses: codecov/codecov-action@v3
